export const passwordResetconfirmTypes={
    PASSWORDRESETCONFIRM_REQUEST:'PASSWORD_RESET_CONFIRM_REQUEST',
    PASSWORDRESETCONFIRM_SUCCESS:'PASSWORD_RESET_CONFIRM_SUCCESS',
    PASSWORDRESETCONFIRM_FAIL:'PASSWORD_RESET_CONFIRM_FAIL'
}