export const passwordResetconfirmTypes={
    PASSWORDRESETCONFIRM_REQUEST:'USER_PASSWORD_RESET_CONFIRM_REQUEST',
    PASSWORDRESETCONFIRM_SUCCESS:'USER_PASSWORD_RESET_CONFIRM_SUCCESS',
    PASSWORDRESETCONFIRM_FAIL:'USER_PASSWORD_RESET_CONFIRM_FAIL'
}